name: Deploy to Trigger.dev (prod)

on:
  push:
    branches:
      - main

env:
  DIRECT_URL:"postgres://postgres.lvuyflawvbeqhnugzhqw:samosa-stats-prod-db@aws-0-us-east-1.pooler.supabase.com:5432/postgres"
  DATABASE_URL:"postgres://postgres.lvuyflawvbeqhnugzhqw:samosa-stats-prod-db@aws-0-us-east-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: 🚀 Deploy Trigger.dev
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
        run: |
          npm run deploy:trigger
